jwtauth/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (TokenObtainPairView,TokenRefreshView,)
from jwtauth import views

urlpatterns = [
     path('usercreation',views.usercreation,name='usercreation'),
     path('userlogin',views.userlogin,name='userlogin'),
     path('userlogout',views.userlogout,name='userlogout'),
     path('home',views.home,name='home'),
     path('emailcreation',views.emailcreation.as_view(),name='emailcreation'),
     path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
     path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh')
]

machineTest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='index.html')),
    path('auth/',include('jwtauth.urls'))

]

jwtauth/models.py
from django.db import models
from django.contrib.auth.models import User
from django .dispatch import receiver
from django.db.models.signals import post_save
from datetime import datetime
from django.utils.timezone import is_naive
import pytz
from jwtauth.task import shedule_email



class EmailPush(models.Model):
    reciever=models.EmailField(max_length=100)
    subject=models.CharField(max_length=200)
    message=models.CharField(max_length=500)
    Push_time=models.DateTimeField()
    email_send=models.BooleanField(default=False)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.reciever}+_+{self.Push_time}"
         


@receiver(post_save, sender=EmailPush)
def shedule_email_create(sender,instance,created,**kwargs):
        
        if created:
            want_time=instance.Push_time
            indian_timezone = pytz.timezone('Asia/Kolkata')
            custom_datetime = datetime(want_time.year, want_time.month, want_time.day, want_time.hour, want_time.minute)  # Naive datetime

            if is_naive(custom_datetime):
                custom_datetime = indian_timezone.localize(custom_datetime)
                    
            shedule_email.apply_async(args=[instance.id], eta=custom_datetime)
























            #     push_time = instance.Push_time.astimezone(pytz.utc)
        #     print('mnt',push_time.minute)
        #     print('hour=',push_time.hour)
        #     print('day_of_month=',push_time.day)
        #     print('month',push_time.month)
        #     # print('day_of_week',push_time.week)
        #     crontab_schedule, created = CrontabSchedule.objects.get_or_create(
        #     minute=push_time.minute,
        #     hour=push_time.hour,
        #     day_of_month=push_time.day,
        #     month_of_year=push_time.month,
        # )

        # # Create a periodic task linked to this crontab
        #     PeriodicTask.objects.create(
        #         crontab=crontab_schedule,
        #         name=f"Send Email Task for {instance.id}",
        #         task='jwtauth.task.shedule_email',  # The task name as per your Celery task
        #         args=json.dumps([instance.id]),  # Arguments to the task, passed as a JSON array
        #         one_off=True  # Make sure this task only runs once
        #     )

jwtauth/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout
from rest_framework_simplejwt.tokens import RefreshToken
from django.http import JsonResponse,HttpResponse
from rest_framework.views import APIView
from django.template.loader import render_to_string
from rest_framework.decorators import api_view, permission_classes,authentication_classes
from rest_framework.response import Response
from jwtauth.customauthentication import CustomAuthentication
from jwtauth.logincheck import login_url_check
from jwtauth.form import EmailForm
from django.utils.decorators import method_decorator
import json
from django.core.mail import send_mail
from django.conf import settings
import pytz
from datetime import datetime



def usercreation(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('userlogin')
        
        return render(request,'registration.html',{'form':form})
    else:
        form=UserCreationForm()
        return render(request,'registration.html',{'form':form})
    

def userlogin(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        usr=authenticate(username=username,password=password)
        if usr is not None:            
            next_url=request.GET.get('next')
            refresh = RefreshToken.for_user(usr)
            if next_url:
                spl=next_url.split('/auth/')[-1]
                reverse_url=reverse(spl)
                response = HttpResponse(status=302)
                response['Location'] = reverse_url
            else:
                response=redirect('home')
            
            response.set_cookie('refresh_token', str(refresh), httponly=True)
            response.set_cookie('access_token', str(refresh.access_token), httponly=True)
            return response            
        
        return render(request,'login.html')
    else:
        try:
            token = request.COOKIES.get('refresh_token')
            if token is None:
                return render(request,'login.html')
            return redirect('home')
        except:
            return render(request,'login.html')

def userlogout(request):   
    response=redirect('userlogin')
    response.delete_cookie('refresh_token')  
    response.delete_cookie('access_token') 
    return response


@login_url_check
@api_view(['GET'])
@authentication_classes([CustomAuthentication])
def home(request):     
    return render(request,'home.html')

@method_decorator(login_url_check, name='dispatch')
class emailcreation(APIView):
    authentication_classes=[CustomAuthentication]
    def get(self,request):
        form=EmailForm()
        return render(request,'email.html',{'form':form})
    def post(self,request,*args,**kwargs):
        form=EmailForm(request.POST)
        if form.is_valid():
            email=form.save(commit=False)
            email.user=request.user
            email.save()
            return redirect('home')
        return render(request,'email.html',{'form':form})

jwtauth/templates/email.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Email sheduler</title>
        <!-- Include Bootstrap CSS -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <style>
            table{
                width: 100%;
            }
            #id_reciever,#id_Push_time,#id_subject,#id_message{
                width: 100%;
            }
        </style>
    </head>
    <body >
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-md-6"> 
                    <h3 class="text-center">shedule email</h3> 
                    <form method="post" action="{% url 'emailcreation' %}" >
                        {% csrf_token %}
                        <table>
                            <tbody>
                                <tr>
                                   <div class="form-group">
                                        <td>
                                            <label for="id_reciever">recipient</label>
                                        </td>
                                        <td>
                                             {{form.reciever}}
                                        </td>
                                    </div>  
                                </tr>
                                <tr>
                                    <div class="form-group">
                                         <td>
                                             <label for="id_subject">subject</label>
                                         </td>
                                         <td>
                                              {{form.subject}}
                                         </td>
                                     </div>  
                                </tr>
                                <tr>
                                    <div class="form-group">
                                         <td>
                                             <label for="id_message">message</label>
                                         </td>
                                         <td>
                                              {{form.message}}
                                         </td>
                                     </div>  
                                </tr>
                                <tr>
                                    <div class="form-group">
                                         <td>
                                             <label for="id_Push_time">sheduled time</label>
                                         </td>
                                         <td>
                                              {{form.Push_time}}
                                         </td>
                                     </div>  
                                </tr>
                                
                            </tbody>
                        </table>
                        <button type="submit"class="btn btn-primary btn-block">create email</button>
                    </form>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>            
    </body>
</html>

jwtauth/templates/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>home Page</title>
        <style>
            a{
              display: block;
              color: black;
             }
            p{
                text-align: center;
            } 
        </style>
    </head>
    <body>
       <h2 style="text-align: center;">home Page</h2>
       <p><a href="{% url 'emailcreation' %}">shedule Email</a></p>
       <p><a href="{% url 'userlogout' %}">logout</a></p>

    </body>
</html>

jwtauth/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>django app</title>
        <style>
            a{
              display: block;
              color: black; 
             }
             .txtcent{
                text-align: center;
             }
        </style>
    </head>
    <body>
       <h2 style="text-align: center;">Index Page</h2>
        <p class="txtcent"><a href="{% url 'home' %}">Dashboard</a></p>
        <p class="txtcent"><a href="{% url 'usercreation' %}">user registration</a></p>
        <p class="txtcent"><a href="{% url 'userlogin' %}">login</a></p>   
    </body>
</html>

jwtauth/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>login</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <style>
            /* #username{
                width: 100%;
            } */
        </style> 
    </head>
    <body>
        
    <!-- <script>
        function handleLogin(event) {
            console.log('login click')
            event.preventDefault();
            const form = event.target;
            console.log(form)
            const formData = new FormData(form);
            
            fetch(form.action, {
                method: 'POST',
                body: formData,
            })
            .then(response => response.json())
            .then(data => {
                console.log(data)
                if (data.next_url) {
                    window.location.href = data.next_url;
                } else {
                    alert(data.message || 'Login failed');
                }
            });
        }
             onsubmit="handleLogin(event)"
    </script> -->
        <div class="container" style="height: 100vh;">
            <div class="row h-100  d-flex justify-content-center align-items-center">
              <div class="col-md-6">
                <form method="post" action="{% url 'userlogin' %}?next={{request.GET.next}}"
                      class="w-100 h-100 d-flex justify-content-center align-items-center 
                      flex-column border py-5 rounded">
                     <!-- style="width: 100%; height: 100vh; display: flex; flex-direction: column; justify-content:center;
                   align-items: center; gap: 10px;" -->
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">username</label>
                    <input type="text"  id="username" placeholder="username" name="username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" placeholder="password" name="password">

                </div>
                <button type="submit" class="btn btn-primary btn-block w-50">login</button>
            </form>
            </div>
           </div> 
        </div> 
       
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> 
    </body>
</html>

jwtauth/templates/registration.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>User Creation</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <style>
            #pswdhelp,#usrhelp{
                display: none;
            }
            #id_username,#id_password2,table{
                width: 100%;
            }
        </style>
    </head>
    <body>
        <div class="container" style="height: 100vh;">
            <div class="row h-100 d-flex justify-content-center align-items-center">
                <div class="col-md-6 border p-5 rounded">
                    <h3 class="text-center">user registeration</h3> 
                    <form method="post" action="{% url 'usercreation' %}"  >
                        {% csrf_token %}
                        <table>
                         <tbody>
                            <tr>
                                <div class="form-group">
                                    <td>
                                        <label for="id_username">Username</label>
                                    </td>
                                    <td class="d-flex flex-column w-100">
                                        {{form.username}}
                                        <small id="usrhelp">{{form.username.help_text}}</small>
                                    </td>
                                </div>
                            </tr>
                            <tr>
                                <div class="form-group">
                                    <td style="position: relative;">
                                        <label for="id_password1" style="position: absolute; top:0">Password </label>
                                    </td>
                                    <td class="d-flex flex-column">
                                        {{form.password1}}
                                        <small id="pswdhelp">{{form.password1.help_text}}</small>
                                    </td>
                                </div> 
                            </tr>
                            <tr>
                                <div class="form-group">
                                    <td>
                                        <label for="id_password2">conform Password </label>
                                    </td>
                                    <td>
                                        {{form.password2}}
                                    </td>
                                </div> 
                            </tr>    
                        </table>
                        <button type="submit"class="btn btn-primary btn-block">register user</button>
                    </form>
                </div>
            </div>
        </div>
        <script>
            document.getElementById('id_password1').addEventListener('focus',function(){
                document.getElementById('pswdhelp').style.display='block';
            })
            document.getElementById('id_password1').addEventListener('blur',function(){
                document.getElementById('pswdhelp').style.display='none';

            })
            document.getElementById('id_username').addEventListener('focus',function(){
                document.getElementById('usrhelp').style.display='block';
            })
            document.getElementById('id_username').addEventListener('blur',function(){
                document.getElementById('usrhelp').style.display='none';

            })
        </script>    
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>     
    </body>
</html>